version: '3'
services:
  app:
    build: .
    depends_on:
      - "postgres"
    environment:
      - TOKEN
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  postgres:
    image: postgres
    volumes:
      - /Users/zhambyl/qwe/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB