version: '2'
services:
  app:
    ports:
      - "80:80"
    build: 
        context: .
        dockerfile: Dockerfile_prod
    depends_on:
      - "postgres"
    env_file:
      - conf.env
  postgres:
    image: postgres
    volumes:
      - /Users/zhambyl/qwe/data:/var/lib/postgresql/data
    env_file:
          - conf.env